### ISSUE TITLE
HW3 tasks

### ISSUE THREAD

**Issue by zackedwards** [zackedwards/modSim#1]
### Tasks for HW3 in modSim

- [x] Upload github profile picture
- [x] Setup Project Teams
- [x]  Solve the first 4 levels in https://learngitbranching.js.org/ 
* Introduction Sequence (5 points)
* Ramping Up (5 points)
* Moving Work Around (5 points)
* A Mixed Bag (5 points)
- [x]  Create a GitHub Issue
